import{a as h,i as m,S as L}from"./assets/vendor-CZwys2ms.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const f=r=>`
  <li class="gallery-card">
    <a href="${r.largeImageURL}">
      <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" />
    </a>
    <p>likes ${r.likes}</p>
    <p>views ${r.views}</p>
    <p>comments ${r.comments}</p>
    <p>downloads ${r.downloads}</p>
  </li>
  `;h.defaults.baseURL="https://pixabay.com/api/";const g=(r,t)=>{const s={params:{key:"45457641-ce63f5c92c9f6494e7448790b",q:r,orientation:"horizontal",page:t,per_page:15,image_type:"photo",safesearch:"true"}};return h.get("",s)},n=document.querySelector(".js-search-form"),l=document.querySelector(".js-gallery"),y=document.querySelector(".loader"),u=document.querySelector(".load-more");let i=1,d="";const b=()=>{y.classList.remove("is-hidden")},p=()=>{y.classList.add("is-hidden")},v=async r=>{try{r.preventDefault(),i=1,d=n.elements.user_query.value,b();const t=await g(d,i);if(console.log(t),t.data.hits.length===0){m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.innerHTML="",n.reset(),p();return}const s=t.data.hits.map(e=>f(e)).join("");l.innerHTML=s,n.reset(),p(),new L(".js-gallery a",{captionsData:"alt",captionDelay:250}).refresh(),u.classList.remove("is-hidden")}catch(t){console.log(t)}},w=async r=>{try{i++;const t=await g(d,i),s=t.data.hits.map(o=>f(o)).join("");l.insertAdjacentHTML("beforeend",s);const{height:a}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"});const e=Math.ceil(t.data.totalHits/15);i>=e&&(u.classList.add("is-hidden"),m.info({title:"info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.log(t)}};n.addEventListener("submit",v);u.addEventListener("click",w);
//# sourceMappingURL=index.js.map
